### ISSUE TITLE
如何在Appdelegate里面对MRRouter进行配置

### ISSUE THREAD

**Issue by icofans** [jiaopen/MRRouter#1]
如何在Appdelegate里面对MRRouter进行配置，配置defaultExecutingBlock和postfix，因为MRRouter是一个单利，因为配置一次就可以，放在Appdelegate比较好管理。这个时候还没有nav，能否在跳转前获取到当前VC  在MRRouter配置默认的跳转方式就可以

- (UIViewController *)currentViewController {
    
    UIViewController * currVC = nil;
    UIWindow *window = [UIApplication sharedApplication].keyWindow;
    UIViewController * Rootvc = window.rootViewController ;
    do {
        if ([Rootvc isKindOfClass:[UINavigationController class]]) {
            UINavigationController * nav = (UINavigationController *)Rootvc;
            UIViewController * v = [nav.viewControllers lastObject];
            currVC = v;
            Rootvc = v.presentedViewController;
            continue;
        }else if([Rootvc isKindOfClass:[UITabBarController class]]){
            UITabBarController * tabVC = (UITabBarController *)Rootvc;
            currVC = tabVC;
            Rootvc = [tabVC.viewControllers objectAtIndex:tabVC.selectedIndex];
            continue;
        } else {
            currVC = Rootvc;
            Rootvc = nil;
        }
    } while (Rootvc!=nil);
    
    return currVC;
}

**Comment by jiaopen** [comment]
defaultExecutingBlock在执行的时候，nav肯定已经创建好了，因为此时页面已经要进行跳转操作了，如果此时连nav都没创建，操作源是从哪来的呢？

**Comment by icofans** [comment]
使用过程中
在iOS10.3.2中        if (NO == [classType isSubclassOfClass:self]) 这句代码在遇到一个WKNSError的classType崩溃了

**Comment by icofans** [comment]
很棒的 ，不过某些场景下可能使用者只想初始化并传递参数，并不做跳转，而是交给其他控制器管理，这种情况是否应该提供只初始化的方式

+ (UIViewController *)instantiateViewControllerWithURL:(NSString *)URLPattern
{
    return [self instantiateViewControllerWithURL:URLPattern parameters:nil];
}

+ (UIViewController *)instantiateViewControllerWithURL:(NSString *)URLPattern parameters:(NSDictionary *)parameters
{
    if (!URLPattern.length && ![self canOpenURL:URLPattern]) {
        return nil;
    }
    NSURL* URL = [NSURL URLWithStringByAddingPercentEncoding:URLPattern];
    NSMutableDictionary *URLParameters = [NSMutableDictionary dictionary];
    
    if (URL.query.length) {
        NSArray* paremeterDataArray = [URL.query componentsSeparatedByString:@"&"];
        for (NSString* paramString in paremeterDataArray) {
            NSArray* paramArr = [paramString componentsSeparatedByString:@"="];
            if (paramArr.count > 1) {
                NSString* key = [[paramArr objectAtIndex:0] stringByRemovingPercentEncoding] ?: @"";
                NSString* value = [[paramArr objectAtIndex:1] stringByRemovingPercentEncoding] ?: @"";
                [URLParameters setObject:value forKey:key];
            }
        }
    }
    [URLParameters addEntriesFromDictionary:parameters];
    
    _MRRoute* route = [[MRRouter sharedInstance] routeWithURL:URLPattern];
    route.parameters = [URLParameters copy];
    
    id object = [[MRRouter sharedInstance] objectWithName:route.className parameters:route.parameters];
    NSAssert(object, @"Could not initialize an instance from the url: %@", route.pattern);
    if (![object valueForKey:@"mr_url"])
    {
        [object setValue:route.pattern forKey:@"mr_url"];
    }
    [object parseParameters];
    return object;
}

**Comment by jiaopen** [comment]
iOS10.3的问题已经处理

**Comment by jiaopen** [comment]
你说的这种场景，可以手动调用
+ (void)registerURL:(NSString *)URLPattern executingBlock:(MRExecutingBlock)executingBlock;
在executingBlock中返回实例

MRRouter的目的是为了解耦，不仅仅为页面跳转服务的，而是为中介者模式服务，现有提供的接口也基本能满足需求。
当有特殊需求时，只要在中介者模式的范畴内，都是可以解决的
